const blockTypes = {
	bulleted_list_item: "bulleted_list_item",
	paragraph: "paragraph",
	heading_1: "heading_1",
	heading_2: "heading_2",
	heading_3: "heading_3",
	code: "code",
	image: "image",
	divider: "divider",
	quote: "quote",
	numbered_list_item: "numbered_list_item",
	toggle: "toggle",
	column_list: "column_list",
	column: "column",
	callout: "callout",
	to_do: "to_do",
	video: "video",
	child_database: "child_database",
	bookmark: "bookmark",
	breadcrumb: "breadcrumb",
	child_page: "child_page",
	embed: "embed",
	equation: "equation",
	file: "file",
	link_preview: "link_preview",
	mention: "mention",
	pdf: "pdf",
	synced_block: "synced_block",
	table: "table",
	table_of_contents: "table_of_contents",
	template: "template",
};

export default blockTypes;
